### ISSUE TITLE
Response.name for high-dimensional tables

### ISSUE THREAD

**Issue by pbahr** [yihui/printr#16]
Thanks for the useful package. I'm printing a 3-dimensional table as the result of `prop.table()` call. In the code, `as.data.table()` is called for high-dimensional tables, which uses `response.name= "Freq"` by default. "Freq" response name is misleading in my case, but I don't think there is a way to change it.

**Comment by yihui** [comment]
Could you provide a minimal example?

**Comment by pbahr** [comment]
```
library(printr)

a <- c(T,F)
b <- factor(1:3)
c <- c("V", "W", "X", "Y", "Z")
d <- 1:100
df <- data.frame(cbind(a,b,c,d))

tab <-table(df$a, df$b, df$c)

tab
prop.table(tab)
```

"Freq" makes sense for the column name of the first table (tab), but not for the second table (prop.table). I would like to name it "Proportion", but not sure if it's possible.

**Comment by yihui** [comment]
OK, I see what you mean now. I provided one possible solution in the current devel version of printr, although I don't quite like the syntax:

    ```{r}
    library(printr)
    
    a <- c(T,F)
    b <- factor(1:3)
    c <- c("V", "W", "X", "Y", "Z")
    d <- 1:100
    df <- data.frame(cbind(a,b,c,d))
    
    tab <-table(df$a, df$b, df$c)
    
    tab
    ```
    
    ```{r printr.table2df.args=list(responseName = 'Proportion')}
    prop.table(tab)
    ```

**Comment by pbahr** [comment]
Thanks, @yihui for the workaround. That would solve it for now.
