### ISSUE TITLE
Consider the option rmarkdown.pandoc.to

### ISSUE THREAD

**Issue by yihui** [yihui/printr#2]
See https://github.com/rstudio/rmarkdown/commit/e6f8a779818aaff605e269f6ca58accbb166516c

When printing an object, we need to consider two types of output formats:

1. `opts_knit$get('out.format')` is for general document formats, e.g. Rnw, Rhtml, Rmd, Rrst, ...
1. `opts_knit$get('rmarkdown.pandoc.to')` is for R Markdown only

**Comment by JanSchulz** [comment]
Not sure from the comment, but this seems related: https://github.com/IRkernel/IRkernel/issues/59

The issue is about getting output in a suitable format (-> multiple mimetypes: plain text, markdown, html) for the rkernel for the jupyter notebook.

**Comment by flying-sheep** [comment]
yeah, your idea to join efforts is great. we could probably rip out the actual code from `printr`/`knitr` and create a lean library that provides them without depending on `printr`, `knitr` or `IRkernel`.

**Comment by yihui** [comment]
Sorry, but I don't have the bandwidth to work on that at the moment. I understand a separate lean package can be nice, though.

This particular issue for the printr repo has been solved, so I'm closing it now.
