### ISSUE TITLE
Error when using summary()

### ISSUE THREAD

**Issue by elinw** [yihui/printr#21]
base::summary() causes a fatal error when present in a markdown file with printr.

Reproducible example
````
     library(printr)  
     summary(iris$Sepal.Length)
````

generates
`Error in provideDimnames(x, sep = sep, base = base) : 
  'dimnames' applied to non-array
Calls: <Anonymous> ... eval -> eval -> data.frame -> do.call -> provideDimnames`

` dimnames(summary(iris$Sepal.Length))`  is NULL

Using `as.array(summary(iris$Sepal.Length))`   solves it, but it was definitely unexpected by me at least.

**Comment by elinw** [comment]
Wow already fixed in master, nice!

**Comment by octaviocipo** [comment]
Thank you, you are wonderful person

**Comment by elenipb** [comment]
Thank you so so so much!!!! I was stuck and thanks to your solution I was able to solve it!
