### ISSUE TITLE
"[" trips up printing

### ISSUE THREAD

**Issue by t-kalinowski** [yihui/printr#22]
```{r help page,  render.args=list(help=list(sections=c('description', 'format')))}
    ?ToothGrowth
    ```
produces:

![screen shot 2016-09-19 at 12 00 17 pm](https://cloud.githubusercontent.com/assets/8462255/18639129/ae1e41f8-7e60-11e6-9dbf-21ff101fff0d.png)

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
