### ISSUE TITLE
vignette not included

### ISSUE THREAD

**Issue by dmenne** [yihui/printr#25]
I know where to find the vignette, but it is not included in the distribution (0.0.6). So the mentioned

`vignette('printr', package = 'printr')`

does not work

**Comment by yihui** [comment]
Not sure if you read README: https://github.com/yihui/printr#printr Chances are you installed the package via `devtools::install_github()`, which does not install package vignettes by default (which is very confusing).

**Comment by dmenne** [comment]
Correct. I had forgotten that problem with devtools
