### ISSUE TITLE
Plan to upload printr to CRAN?

### ISSUE THREAD

**Issue by ronammar** [yihui/printr#29]
Is there a plan to upload the `printr` package to CRAN?

**Comment by yihui** [comment]
No, there are a few things that I don't like, and I need more time to think about them. Is there a particular reason why you want it to be on CRAN?

**Comment by ronammar** [comment]
Thanks for the reply. Main reason is that it  would make it easier for colleagues to install dependencies in my markdown reports that use printr. Since the package has been around so long perhaps you could upload the current stable build? Thanks again!

**Comment by yihui** [comment]
I mean there are a few things I may want to change before a CRAN release, and I need to think about them. Please feel free to ping me again in a month. Thanks!

**Comment by jasonserviss** [comment]
I will ping for @ronammar since I am really looking forward to a CRAN release as well!

**Comment by ronammar** [comment]
Ping! Hi @yihui! What are your thoughts RE CRAN release? Thanks

**Comment by yihui** [comment]
I just uploaded it to CRAN. Not sure if it will pass. Finger-crossed.

**Comment by ronammar** [comment]
This is an excellent and important package, so I'm sure it'll pass. Thanks, @yihui!

**Comment by yihui** [comment]
On CRAN now: https://cran.r-project.org/web/packages/printr/ 🎉
