### ISSUE TITLE
knit_print.help_files_with_topic

### ISSUE THREAD

**Issue by yihui** [yihui/printr#3]
see http://www.noamross.net/blog/2013/6/18/helpconsoleexample.html

also [help.search()](http://stackoverflow.com/q/23746378/559676)

also http://stackoverflow.com/q/24146843/559676

**Comment by dhjones1** [comment]
This has stopped working for me.

**Comment by yihui** [comment]
@dhjones1 You have already filed an issue to https://github.com/yihui/knitr/issues/1314, so please do not repeat it here.
