### ISSUE TITLE
Support for matrices

### ISSUE THREAD

**Issue by expersso** [yihui/printr#31]
I can't seem to get matrices to print with this package. Everything works fine for dataframes, ?foo, etc, but not matrices. The screenshot summarizes the situation.

![printr](https://cloud.githubusercontent.com/assets/7280464/25554655/ccc7d3b4-2cd2-11e7-975c-575f9573da92.png)

**Comment by yihui** [comment]
This has been fixed in **knitr**. You can install the development version via

```r
devtools::install_github('yihui/knitr')
```

**Comment by wikithink** [comment]
Kable with 2 column  but 0 rows data frame ends up with  <p> tag in generated HTML,no thead,no tbody

**Comment by yihui** [comment]
When you [cross-post issues](https://yihui.name/en/2017/10/cross-posting/), please mention it. Let's keep everyone in the same thread: https://github.com/yihui/knitr/issues/1677 Thanks!
