### ISSUE TITLE
format 1-dim table in multiple lines

### ISSUE THREAD

**Issue by peranti** [yihui/printr#32]
How to fit the table output according to the page width when using `printr` table function?

    table(sample(stringi::stri_rand_strings(20, 3), 200, replace = TRUE))

![2](https://user-images.githubusercontent.com/9472741/28996126-19dc2bce-7a02-11e7-8312-53dcceab16a4.png)

The output of the above code exceeds the page width. How to print the table into multiple lines if the width is exceeding the page width?

- setting the width `options(width = 10)` did not help either.

**Comment by yihui** [comment]
Closing because it has been asked on SO: https://stackoverflow.com/q/45522678/559676
