### ISSUE TITLE
printr doesn't work when used outside RStudio

### ISSUE THREAD

**Issue by fmichonneau** [yihui/printr#6]
If I run this from the terminal

```
curl https://raw.githubusercontent.com/yihui/printr/master/vignettes/printr.Rmd > /tmp/printr.Rmd; Rscript -e 'library(knitr); library(printr); knit2html("/tmp/printr.Rmd")'
```

the file produced doesn't have the pretty tables

![screenshot from 2015-03-17 18 35 11](https://cloud.githubusercontent.com/assets/5502922/6692281/814b885a-ccd4-11e4-94e5-3d9b6a2381a5.png)

However, I knit the vignette in RStudio it works fine.

**Comment by yihui** [comment]
RStudio is irrelevant here. You are supposed to render the vignette using `rmarkdwon::render()` instead of `knitr::knit2html()`. The latter is R Markdown v1, and does not support Markdown tables without table headers.

**Comment by fmichonneau** [comment]
Thanks Yihui!
