### ISSUE TITLE
Missing style?

### ISSUE THREAD

**Issue by ronammar** [yihui/printr#7]
When knitting the vignette to html, the table formatting is absent (except for the bold text in the table header). Is there supposed to be an additional style sheet?

![capture](https://cloud.githubusercontent.com/assets/5419280/8014115/fbab4a8a-0b9b-11e5-8693-880a3c73c190.PNG)

**Comment by yihui** [comment]
You can apply whatever CSS styles you like to your document if you use R Markdown v2: http://rmarkdown.rstudio.com/html_document_format.html It looks like you are still using v1, in which case you need to read the documentation `?markdown::markdownToHTML` to know how to customize CSS.
