### ISSUE TITLE
compatibility with microbenchmark

### ISSUE THREAD

**Issue by ignacio82** [yihui/printr#8]
I cannot make `printr` and `microbenchmark` work well together. For example:

    ---
    title: "test"
    author: "Ignacio"
    output: html_document
    ---
    
    ```{r}
    library(printr)
    library(microbenchmark)
    a1 <- a2 <- a3 <- a4 <- numeric(0)
    
    res <- microbenchmark(a1 <- c(a1, 1),
                          a2 <- append(a2, 1),
                          a3[length(a3) + 1] <- 1,
                          a4[[length(a4) + 1]] <- 1,
                          times=100L)
    tbl<-print(res)
    tbl
    ```

Prints the table twice, once with good formatting and one without. If i change

    tbl<-print(res)
    tbl

to just

    print(res)

I get the table without formatting.

Thanks!

**Comment by yihui** [comment]
Use `summary()` instead, which returns a data frame without printing it:

    ---
    title: "test"
    author: "Ignacio"
    output: html_document
    ---
    
    ```{r}
    library(printr)
    library(microbenchmark)
    a1 <- a2 <- a3 <- a4 <- numeric(0)
    
    res <- microbenchmark(a1 <- c(a1, 1),
                          a2 <- append(a2, 1),
                          a3[length(a3) + 1] <- 1,
                          a4[[length(a4) + 1]] <- 1,
                          times=100L)
    summary(res)
    ```

**Comment by ignacio82** [comment]
Thanks!
