### ISSUE TITLE
kable() and the margin of the page

### ISSUE THREAD

**Issue by parre07** [yihui/printr#9]
Hy all!

I want to control the way the table is printed using the kable function().

Instead of printing like this: (Because I don't like the extra space between columns) 
![capture2](https://cloud.githubusercontent.com/assets/13880005/9374695/d528902a-46ce-11e5-977d-f7f1f336bce7.PNG)

I would like to print like this: 
![capture](https://cloud.githubusercontent.com/assets/13880005/9374701/df2491a0-46ce-11e5-94b3-7e6826b66b45.PNG)

I saw that depending on the template, the output of kable is different. How can I control it?

Thanks in advance,
Guilherme

**Comment by yihui** [comment]
I guess Bootstrap probably defined the table width to be 100%, and you can override it using custom CSS: http://rmarkdown.rstudio.com/html_document_format.html#appearance-and-style

BTW, next time you may try StackOverflow if you have questions: http://stackoverflow.com/questions/tagged/rmarkdown I don't really keep track of general questions in Github issues, and sometimes it is easy to forget them.

**Comment by parre07** [comment]
Tks Yihui!!

Good luck on your projects!!
